# Generated by Django 5.1.2 on 2024-11-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
    ]
